config/routes.rb
Rails.application.routes.draw do
  devise_for :users
    # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users, only: [:index, :show] do
    resources :posts,  only: [:index, :show, :new,:create] do
      resources :comments, only: [:new, :create]
      resources :likes, only: [:new, :create]
    end
  end
  # Defines the root path route ("/")
  root 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates :Text, presence: true

  def update_comments_counter
    post.update(CommentsCounter: post.comments.count)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user

  def update_likes
    post.update(LikesCounter: post.likes.count)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments # Post can have 0 or more comments
  has_many :likes # Posts can have 0 or more likes
  validates :Title, presence: true, length: { in: 3..250 }
  validates :CommentsCounter, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :LikesCounter, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def posts_counter
    user.update(PostsCounter: user.posts.count)
  end

  def recent_comments
    comments.includes(:post).order(created_at: :DESC).limit(5)
  end

  def all_comments
    comments.includes(:post).order(created_at: :DESC)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts # user can have many posts
  has_many :comments, through: :post # User can have 0 or more comments in one
  has_many :likes, through: :post
  validates :name, presence: true, length: { in: 3..32 }
  validates :PostsCounter, presence: true, comparison: { greater_than_or_equal_to: 0 },
                           numericality: { only_integer: true }
  def first_three_posts
    posts.includes(:user).order(created_at: :DESC).limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!
  before_action :update_allowed_parameters, if: :devise_controller?

  def all_users
    User.all
  end

  def recent_posts(id)
    user = User.find_by(id:)
    user.first_three_posts
  end

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :surname, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :surname, :email, :password, :password_confirmation)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    respond_to do |format|
      format.html { render :new, locals: { comment: Comment.new } }
    end
  end

  def create
    user = current_user
    post = Post.find_by(id: post_params.to_i)
    comment = Comment.new(comment_params)
    comment.user = user
    comment.post = post

    if comment.save
      flash[:notice] = 'Comments saved successfully'
      comment.update_comments_counter
      redirect_to user_post_url(id: post.id)
    else
      flash[:alert] = 'Error: Comments could not be saved'
      redirect_to user_post_url(id: post_id)
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:Text)
  end

  def post_params
    params.require(:post_id)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def new
    respond_to do |format|
      format.html { render :new, locals: { like: Like.new } }
    end
  end

  def create
    user = current_user
    post_id = params[:post_id]
    post = Post.find_by(id: post_id.to_i)
    params.permit!
    like = Like.new
    like.user = user
    like.post = post

    if like.save
      like.update_likes
    else
      flash[:alert] = 'Error: Like could not be saved'
    end
    redirect_to user_post_url(id: post_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user_posts = Post.where(user_id: params[:user_id]).order(created_at: :DESC)
    @user_info = User.find_by(id: params[:user_id])
  end

  def show
    @post_info = Post.find_by(id: params[:id])
  end

  def new
    respond_to do |format|
      format.html { render :new, locals: { post: Post.new } }
    end
  end

  def create
    user = current_user
    post = Post.new(post_params)
    post.user = user

    if post.save
      post.posts_counter
      flash[:notice] = 'Post saved successfully'
      redirect_to user_posts_url
    else
      flash[:alert] = 'Error: Post could not be saved'
      redirect_to new_user_post_url
    end
  end

  private

  def post_params
    params.require(:post).permit(:Title, :Text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = all_users
  end

  def show
    my_id = params[:id]
    @user_info = User.find_by(id: my_id.to_i)
    @recent_posts = recent_posts(my_id.to_i)
    # @current_user = current_user
    # @user_info = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/comments/_comment.html.erb
<div class="comment">
  <h4><%= comment.user.name %></h4>
  <p><%= comment.Text %></p>
</div>

app/views/comments/new.html.erb
<section class='comment'>
  <%= form_with model: [:user,:post, comment], method: :post do |form|%>
    <%=form.text_area :Text%>
    <%= form.submit "add comment"%>
  <%end%>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>  
    <%= yield %>
  </body>
</html>

app/views/likes/new.html.erb
<section class='like'>
  <%= form_with model: [:user,:post, like], method: :post do |form|%>
    <%= form.submit "Like"%>
  <%end%>
</section>

app/views/posts/_post_byUser.html.erb
<section class="user_posts">
  <%=link_to user_post_path(id:post.id)do%>
  <div class="card-post">
    <h1><%= post.Title%></h1>
    <p><%= post.Text%></p>
    <% commentsCounter = post.CommentsCounter == nil ? '0' : post.CommentsCounter %>
    <% likesCounter = post.LikesCounter == nil ? '0' : post.LikesCounter %>
    <small>
      Comments: <%=commentsCounter%>, Likes: <%=likesCounter%>       
    </small>
  </div>
  <%end%> 

  <div class="comments">
    <%comments=post.recent_comments %>
     <% comments.each do |comment| %>
        <%= render partial: 'comments/comment', locals: {comment: comment} %>
     <%end%>
  </div>
</section>

app/views/posts/_post_info.html.erb
<section class="post-info">
<% commentsCounter = post.CommentsCounter == nil ? '0' : post.CommentsCounter %>
<% likesCounter = post.LikesCounter == nil ? '0' : post.LikesCounter %>
  <header class='my-header'>
    <div class="posts-by">
      <h1><%=post.Title%></h1>
      <h3>by</h3>
      <h3><%=post.user.name%></h3>
    </div>
    <small>
      <%= link_to 'Comments:', new_user_post_comment_path(post_id: post.id)%> <%=commentsCounter%>, 
      <%= link_to 'Likes:', new_user_post_like_path(post_id: post.id) %> <%=likesCounter%>       
    </small>
  </header>

  <div class="post-content">
    <p><%= post.Text %></p>
  </div>
</section>

<section class='user_comments'>
  <%comments=post.all_comments %>
    <% comments.each do |comment| %>
      <%= render partial: 'comments/comment', locals:{comment: comment}%>
    <%end%>
</section>

app/views/posts/_user_posts.html.erb
<section class="posts">
  <h1><%= post.Title%></h1>
  <p><%= post.Text%></p>
  <% commentsCounter = post.CommentsCounter == nil ? '0' : post.CommentsCounter %>
  <% likesCounter = post.LikesCounter == nil ? '0' : post.LikesCounter %>
  <small>
    Comments: <%=commentsCounter%>, Likes: <%=likesCounter%>       
  </small>
</section>

app/views/posts/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>User_posts</title>
</head>
<body>
   <h1><%= link_to 'create post', new_user_post_path %></h1>
  <%= render partial: "users/user",  locals: { user: @user_info } %>
	<% @user_posts.each do |post| %>
		<%= render partial: "post_byUser", locals: { post: post } %>
	<% end %>
</body>
</html>

app/views/posts/new.html.erb
<section class="form-post">
  <%= form_with model: [:user, post], method: :post do |form| %>
    <%= form.text_field :Title %>
    <%= form.text_area :Text%>
    <%= form.submit "Add Post" %>
  <% end %>
</section>

app/views/posts/show.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>post_by_user</title>
</head>
<body>
  <h1>Here is post by user</h1>
   <section class="post-by-person">
     <%= render partial: "post_info", locals:{post: @post_info}%>
   </section>
</body>
</html>

app/views/users/_user.html.erb
<section id="user">
  <img class="image" src="<%=user.photo%>" alt="user-image" />
  <%= link_to user_path(user) do%>
  <div class="card">
     <h2><%= user.name%> </h2>
     <% countPosts = user.PostsCounter == nil ? 0 : user.PostsCounter%>
     <p> Number of posts: <%= countPosts%></p>
  </div class="card">
  <%end%>
</section>

app/views/users/index.html.erb
<%= stylesheet_link_tag "user" %>

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>users</title>
</head>
<body>
	<main id ="container">  
	  <%= render @users %>
  </main>  
</body>
</html>

app/views/users/show.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>User</title>
</head>
<body>
	<section class= 'user'>
	  <%= render @user_info %>
	</section>

	<section id="bio">
		<h6>Bio</h6>
	   <p><%= @user_info.Bio %></p>
	</section>

	<section class="posts-by-user">
	  <% @recent_posts.each do |post| %>
		  <%= render partial: "posts/user_posts", locals: { post: post } %>
	  <% end %>
	</section>
	<%=link_to user_posts_path(@user_info) do%>
	  <button class="see-posts">See all posts</button>
	<%end%>	
</body>
</html>